apiVersion: k3d.io/v1alpha4 # specify the version of the k3d API to use
kind: Simple # specify that this is a cluster resource
metadata:
  name: iot-cluster # specify a name for the cluster
# servers: 1 # control plane node
# agents: 2 # worker nodes
# kubeAPI: # same as `--api-port myhost.my.domain:6445` (where the name would resolve to 127.0.0.1)
#   hostPort: "6445" # where the Kubernetes API listening port will be mapped to on your host system
# ports:
  # - port: 8080:80 # same as `--port '8080:80@loadbalancer'`
    # nodeFilters:
    #   - loadbalancer

